export enum AuthConfig {
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXP = 'JWT_EXP',
  REFRESH_TOKEN_EXP_IN_DAYS = 'REFRESH_TOKEN_EXP_IN_DAYS',
  REFRESH_TOKEN_COOKIES_NAME = 'refresh_token',
  ACCESS_TOKEN_PREFIX = 'Bearer',
}

export const Auth = {
  JWT_EXP_TIME: '5m',
  REFRESH_TOKEN_EXP_TIME_IN_DAYS: 30,
  MIN_PASSWORD_LENGTH: 7,
} as const;
